package com.techingen.twentyatmailhandlerservice.entity;
// Generated 11 Mar, 2011 2:58:42 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer messageId;
     private TwentyatUser twentyatUser;
     private Date datetime;
     private String messageText;
     private Integer parentId;
     private Set<Recipient> recipients = new HashSet<Recipient>(0);

    public Message() {
    }

	
    public Message(TwentyatUser twentyatUser) {
        this.twentyatUser = twentyatUser;
    }
    public Message(TwentyatUser twentyatUser, Date datetime, String messageText, Integer parentId, Set<Recipient> recipients) {
       this.twentyatUser = twentyatUser;
       this.datetime = datetime;
       this.messageText = messageText;
       this.parentId = parentId;
       this.recipients = recipients;
    }
   
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
    public TwentyatUser getTwentyatUser() {
        return this.twentyatUser;
    }
    
    public void setTwentyatUser(TwentyatUser twentyatUser) {
        this.twentyatUser = twentyatUser;
    }
    public Date getDatetime() {
        return this.datetime;
    }
    
    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }
    public String getMessageText() {
        return this.messageText;
    }
    
    public void setMessageText(String messageText) {
        this.messageText = messageText;
    }
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
    public Set<Recipient> getRecipients() {
        return this.recipients;
    }
    
    public void setRecipients(Set<Recipient> recipients) {
        this.recipients = recipients;
    }




}


