package com.techingen.twentyatmailhandlerservice.entity;
// Generated 11 Mar, 2011 2:58:42 PM by Hibernate Tools 3.2.1.GA



/**
 * Recipient generated by hbm2java
 */
public class Recipient  implements java.io.Serializable {


     private Integer id;
     private TwentyatUser twentyatUser;
     private Message message;

    public Recipient() {
    }

    public Recipient(TwentyatUser twentyatUser, Message message) {
       this.twentyatUser = twentyatUser;
       this.message = message;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TwentyatUser getTwentyatUser() {
        return this.twentyatUser;
    }
    
    public void setTwentyatUser(TwentyatUser twentyatUser) {
        this.twentyatUser = twentyatUser;
    }
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }




}


