package com.techingen.twentyatmailhandlerservice.entity;
// Generated 11 Mar, 2011 2:58:42 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TwentyatUser generated by hbm2java
 */
public class TwentyatUser  implements java.io.Serializable {


     private String twentyatUserId;
     private String firstName;
     private String lastName;
     private String email;
     private String mobilePhone;
     private String photo;
     private String friendlyName;
     private String middleName;
     private Long facebookId;
     private Boolean isActive;
     private String streetAddress;
     private String locality;
     private String region;
     private Integer postalCode;
     private String country;
     private String username;
     private Set<TwentyatGroup> twentyatGroups = new HashSet<TwentyatGroup>(0);
     private Set<Recipient> recipients = new HashSet<Recipient>(0);
     private Set<FriendsMapping> friendsMappings = new HashSet<FriendsMapping>(0);
     private Set<ContactPerson> contactPersons = new HashSet<ContactPerson>(0);
     private Set<Message> messages = new HashSet<Message>(0);

    public TwentyatUser() {
    }

	
    public TwentyatUser(String twentyatUserId, String username) {
        this.twentyatUserId = twentyatUserId;
        this.username = username;
    }
    public TwentyatUser(String twentyatUserId, String firstName, String lastName, String email, String mobilePhone, String photo, String friendlyName, String middleName, Long facebookId, Boolean isActive, String streetAddress, String locality, String region, Integer postalCode, String country, String username, Set<TwentyatGroup> twentyatGroups, Set<Recipient> recipients, Set<FriendsMapping> friendsMappings, Set<ContactPerson> contactPersons, Set<Message> messages) {
       this.twentyatUserId = twentyatUserId;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.mobilePhone = mobilePhone;
       this.photo = photo;
       this.friendlyName = friendlyName;
       this.middleName = middleName;
       this.facebookId = facebookId;
       this.isActive = isActive;
       this.streetAddress = streetAddress;
       this.locality = locality;
       this.region = region;
       this.postalCode = postalCode;
       this.country = country;
       this.username = username;
       this.twentyatGroups = twentyatGroups;
       this.recipients = recipients;
       this.friendsMappings = friendsMappings;
       this.contactPersons = contactPersons;
       this.messages = messages;
    }
   
    public String getTwentyatUserId() {
        return this.twentyatUserId;
    }
    
    public void setTwentyatUserId(String twentyatUserId) {
        this.twentyatUserId = twentyatUserId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getFriendlyName() {
        return this.friendlyName;
    }
    
    public void setFriendlyName(String friendlyName) {
        this.friendlyName = friendlyName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public Long getFacebookId() {
        return this.facebookId;
    }
    
    public void setFacebookId(Long facebookId) {
        this.facebookId = facebookId;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public String getStreetAddress() {
        return this.streetAddress;
    }
    
    public void setStreetAddress(String streetAddress) {
        this.streetAddress = streetAddress;
    }
    public String getLocality() {
        return this.locality;
    }
    
    public void setLocality(String locality) {
        this.locality = locality;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public Integer getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(Integer postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Set<TwentyatGroup> getTwentyatGroups() {
        return this.twentyatGroups;
    }
    
    public void setTwentyatGroups(Set<TwentyatGroup> twentyatGroups) {
        this.twentyatGroups = twentyatGroups;
    }
    public Set<Recipient> getRecipients() {
        return this.recipients;
    }
    
    public void setRecipients(Set<Recipient> recipients) {
        this.recipients = recipients;
    }
    public Set<FriendsMapping> getFriendsMappings() {
        return this.friendsMappings;
    }
    
    public void setFriendsMappings(Set<FriendsMapping> friendsMappings) {
        this.friendsMappings = friendsMappings;
    }
    public Set<ContactPerson> getContactPersons() {
        return this.contactPersons;
    }
    
    public void setContactPersons(Set<ContactPerson> contactPersons) {
        this.contactPersons = contactPersons;
    }
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }




}


